### ISSUE TITLE
Add custom CSS via customizer as a non-admin users

### ISSUE THREAD

**Issue by BenBinary** [rotaract/rotaract-family#21]
In the pane on the right hand it is not possible to set css settings. May you can make the feature available for all users it would make some customizations more easy.

**Comment by bbenno** [comment]
This unexpected behavior was due to the missing capabilities `edit_css` as an “Administrator” of a site in a multi-site network.
With the default capabilities applied, only a “Super Administrator” could edit the CSS.
Therefore, this is not a bug of this theme.
